name: spacex_demo
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  crew_member_repository:
    # Clone every own packages into packages/ and use local path
    # if you want to make changes
    # path: packages/crew_member_repository
    git:
      url: https://github.com/yshean/crew_member_repository.git
      ref: main # branch name
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  rocket_repository:
    # path: packages/rocket_repository
    git:
      url: https://github.com/yshean/rocket_repository.git
      ref: main
  spacex_ui:
    # path: packages/spacex_ui
    git:
      url: https://github.com/yshean/spacex_ui.git
      ref: main
  url_launcher: ^6.1.4

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
